apiVersion: v1
kind: ConfigMap
metadata:
  name: machine-config-osimageurl
  namespace: openshift-machine-config-operator
data:
  # The OS payload, managed by the daemon + pivot + rpm-ostree
  # https://github.com/openshift/machine-config-operator/issues/183
  # This gets substituted in at release payload creation time by the
  # machine-os-content imagestream specified in image-references (the string
  # here must match exactly).
  osImageURL: "registry.svc.ci.openshift.org/rhcos/maipo@sha256:83a6d461628380f1dcc057ffef4909992f593b72c5aa4db2e01c0b130004afea"
